# Generated by Django 5.2.7 on 2026-01-07 22:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=1200, validators=[django.core.validators.MinValueValidator(0)])),
                ('peak_rating', models.IntegerField(default=1200)),
                ('games_played', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('W', 'White Win'), ('B', 'Black Win'), ('D', 'Draw')], max_length=1)),
                ('white_rating_before', models.IntegerField()),
                ('black_rating_before', models.IntegerField()),
                ('white_rating_after', models.IntegerField()),
                ('black_rating_after', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player_black', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_black', to='ratings.player')),
                ('player_white', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_white', to='ratings.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='ratings.tournament')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
