# Generated by Django 5.2.7 on 2026-01-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='black_rating_change',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='white_rating_change',
            field=models.IntegerField(default=0),
        ),
    ]
