# Generated by Django 5.2.7 on 2026-01-08 22:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_match_black_rating_change_match_white_rating_change'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='tournament',
            name='current_round',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='num_rounds',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(related_name='tournaments', to='ratings.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(choices=[('SWISS', 'Swiss Tournament'), ('GROUP', 'Group Tournament'), ('MATCHUP', 'Matchups')], default='SWISS', max_length=10),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('group_number', models.IntegerField()),
                ('result', models.CharField(choices=[('W', 'White Win'), ('B', 'Black Win'), ('D', 'Draw')], max_length=1)),
                ('white_rating_before', models.IntegerField()),
                ('black_rating_before', models.IntegerField()),
                ('white_rating_after', models.IntegerField()),
                ('black_rating_after', models.IntegerField()),
                ('white_rating_change', models.IntegerField(default=0)),
                ('black_rating_change', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player_black', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_black', to='ratings.player')),
                ('player_white', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_white', to='ratings.player')),
                ('players', models.ManyToManyField(blank=True, related_name='tournament_groups', to='ratings.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='ratings.tournament')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='ratings.tournament')),
            ],
            options={
                'ordering': ['round_number'],
                'unique_together': {('tournament', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='Pairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('W', 'White Win'), ('B', 'Black Win'), ('D', 'Draw'), ('P', 'Pending')], default='P', max_length=1)),
                ('white_rating_before', models.IntegerField()),
                ('black_rating_before', models.IntegerField()),
                ('white_rating_after', models.IntegerField(blank=True, null=True)),
                ('black_rating_after', models.IntegerField(blank=True, null=True)),
                ('white_rating_change', models.IntegerField(default=0)),
                ('black_rating_change', models.IntegerField(default=0)),
                ('board_number', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player_black', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings_as_black', to='ratings.player')),
                ('player_white', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings_as_white', to='ratings.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings', to='ratings.round')),
            ],
            options={
                'ordering': ['board_number'],
                'unique_together': {('round', 'player_white', 'player_black')},
            },
        ),
        migrations.CreateModel(
            name='TournamentStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('total_score', models.FloatField(default=0.0)),
                ('rating_change', models.IntegerField(default=0)),
                ('initial_rating', models.IntegerField()),
                ('final_rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_standings', to='ratings.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='ratings.tournament')),
            ],
            options={
                'ordering': ['-total_score', '-wins'],
                'unique_together': {('tournament', 'player')},
            },
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
