# Generated by Django 5.2.7 on 2026-01-08 22:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_alter_tournament_options_tournament_current_round_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['group_number']},
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('tournament', 'group_number')},
        ),
        migrations.AddField(
            model_name='tournament',
            name='num_groups',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='tournament',
            name='players_per_group',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='group',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='ratings.tournament'),
        ),
        migrations.RemoveField(
            model_name='group',
            name='black_rating_after',
        ),
        migrations.RemoveField(
            model_name='group',
            name='black_rating_before',
        ),
        migrations.RemoveField(
            model_name='group',
            name='black_rating_change',
        ),
        migrations.RemoveField(
            model_name='group',
            name='player_black',
        ),
        migrations.RemoveField(
            model_name='group',
            name='player_white',
        ),
        migrations.RemoveField(
            model_name='group',
            name='result',
        ),
        migrations.RemoveField(
            model_name='group',
            name='white_rating_after',
        ),
        migrations.RemoveField(
            model_name='group',
            name='white_rating_before',
        ),
        migrations.RemoveField(
            model_name='group',
            name='white_rating_change',
        ),
    ]
