# Generated by Django 5.2.7 on 2026-01-08 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_alter_group_options_alter_group_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('W', 'White Win'), ('B', 'Black Win'), ('D', 'Draw')], max_length=1)),
                ('white_rating_before', models.IntegerField()),
                ('black_rating_before', models.IntegerField()),
                ('white_rating_after', models.IntegerField()),
                ('black_rating_after', models.IntegerField()),
                ('white_rating_change', models.IntegerField(default=0)),
                ('black_rating_change', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player_black', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_black', to='ratings.player')),
                ('player_white', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_white', to='ratings.player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
