# Generated by Django 5.2.7 on 2026-01-08 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0005_player_birth_date_match'),
    ]
    # Migration converted to no-op because the project has been refactored
    # to remove tournament/round/pairing/group models. Keeping this
    # migration as an explicit no-op avoids schema operations that rely
    # on models which no longer exist in the current codebase.
    operations = []
