# Generated by Django 5.2.7 on 2026-01-08 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0007_alter_pairing_unique_together_and_more'),
    ]
    # Converted to no-op after refactor: tournament/round/pairing/group models
    # were removed from the codebase. Keeping this migration as an
    # explicit no-op avoids attempting to alter database schema based on
    # stale model definitions.
    operations = []
