# Generated by assistant to change default player rating to 1500
from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0008_alter_pairing_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rating',
            field=models.IntegerField(default=1500, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='player',
            name='peak_rating',
            field=models.IntegerField(default=1500),
        ),
    ]
