# Generated by Django 5.2.18 on 2026-10-07 19:56
#
# The tournament feature's code was removed earlier without a migration.
# This drops its unused tables, deleting dependents before the models they reference.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0010_match_revert_tracking'),
    ]

    operations = [
        migrations.DeleteModel(name='Pairing'),
        migrations.DeleteModel(name='TournamentStanding'),
        migrations.DeleteModel(name='Round'),
        migrations.DeleteModel(name='Group'),
        migrations.DeleteModel(name='Tournament'),
    ]
